local profile = "user"

require(profile .. ".autocommands")
require(profile .. ".autopairs")
require(profile .. ".bufferline")
require(profile .. ".cmp")
require(profile .. ".colorscheme")
require(profile .. ".comment")
require(profile .. ".gitsigns")
require(profile .. ".impatient")
require(profile .. ".indentline")
require(profile .. ".keymaps")
require(profile .. ".lsp")
require(profile .. ".lualine")
require(profile .. ".nvim-tree")
require(profile .. ".options")
require(profile .. ".plugins")
require(profile .. ".project")
require(profile .. ".telescope")
require(profile .. ".toggleterm")
require(profile .. ".treesitter")
require(profile .. ".whichkey")
-- require(profile .. ".alpha")
-- require(profile .. ".org")
