local profile = "user"

require(profile .. ".autocommands")
require(profile .. ".colorscheme")
require(profile .. ".keymaps")
require(profile .. ".lsp")
require(profile .. ".options")

require(profile .. ".autopairs")
require(profile .. ".cmp")
require(profile .. ".cokeline")
require(profile .. ".comment")
require(profile .. ".gitsigns")
require(profile .. ".impatient")
require(profile .. ".indentline")
require(profile .. ".lualine")
require(profile .. ".nvim-tree")
require(profile .. ".plugins")
require(profile .. ".project")
require(profile .. ".telescope")
require(profile .. ".toggleterm")
require(profile .. ".treesitter")
require(profile .. ".whichkey")
